[package]
name = "assets"
version = "0.2.1"
description = "Asset canister functionality for your canister"
repository = "https://github.com/krpeacock/assets"

[dependencies]
base = "0.10.0"
test = "1.0.1"
